### ISSUE TITLE
>help not implemented

### ISSUE THREAD

**Issue by sterling0x1** [Razzile/ASMBot#1]
It is totally not.

**Comment by Razzile** [comment]
ayyy fuck you mayn

**Comment by futilityteam** [comment]
Some very professional handling of issues.

**Comment by sterling0x1** [comment]
> Some very professional handling of issues.

My feelings were deeply hurt back then in 2016, 3 years were not enough recover completely from the deep depression this answer caused. Without help function all is lost, in 3 years I still didn’t figure out how to use the thing. I hope your concerns about Razzile’s issue handling skills will open his eyes, and finally add that GODDAMN HELP COMMAND! 


Jokes, we’re friends, it was more like a pisstake back then from both end.
